export interface StateData {
  slug: string
  name: string
  abbreviation: string
  stateTaxRate: number
  hasNoIncomeTax: boolean
  notes: string
  brackets?: string
}

// 2025 state income tax data — flat rate or effective rate for middle-income earners
export const US_STATES: StateData[] = [
  { slug: 'alabama', name: 'Alabama', abbreviation: 'AL', stateTaxRate: 4.0, hasNoIncomeTax: false, notes: 'Alabama uses a graduated income tax with rates from 2% to 5%. The top 5% rate applies to income over $3,000 (single). Local taxes may also apply in some counties.', brackets: '2% (under $500), 4% ($500-$3,000), 5% (over $3,000)' },
  { slug: 'alaska', name: 'Alaska', abbreviation: 'AK', stateTaxRate: 0, hasNoIncomeTax: true, notes: 'Alaska has no state income tax — one of seven states with zero state-level income tax. Residents may receive an annual Permanent Fund Dividend (PFD) payment from oil revenue.', brackets: 'No state income tax' },
  { slug: 'arizona', name: 'Arizona', abbreviation: 'AZ', stateTaxRate: 2.5, hasNoIncomeTax: false, notes: 'Arizona implemented a flat 2.5% state income tax rate effective 2023, replacing its previous graduated bracket system. This makes tax calculations straightforward for all income levels.', brackets: 'Flat 2.5%' },
  { slug: 'arkansas', name: 'Arkansas', abbreviation: 'AR', stateTaxRate: 3.9, hasNoIncomeTax: false, notes: 'Arkansas has a graduated tax structure with a top rate of 3.9% (reduced from 4.4% in 2024). The top bracket applies to income over $24,300.', brackets: '2% ($4,400-$8,800), 3% ($8,800-$13,400), 3.4% ($13,400-$22,200), 3.9% (over $22,200)' },
  { slug: 'california', name: 'California', abbreviation: 'CA', stateTaxRate: 9.3, hasNoIncomeTax: false, notes: 'California has the highest top marginal income tax rate in the US at 13.3%, with 9 brackets. For a median income earner around $65,000-$75,000, the effective rate is approximately 8-10%. A 1% Mental Health Services Tax applies to income over $1 million.', brackets: '1% to 13.3% across 9 brackets; top rate over $1M' },
  { slug: 'colorado', name: 'Colorado', abbreviation: 'CO', stateTaxRate: 4.4, hasNoIncomeTax: false, notes: 'Colorado has a flat 4.4% state income tax rate. This was reduced from 4.55% in 2022 via Proposition 121. The flat rate applies to all taxable income levels.', brackets: 'Flat 4.4%' },
  { slug: 'connecticut', name: 'Connecticut', abbreviation: 'CT', stateTaxRate: 5.5, hasNoIncomeTax: false, notes: 'Connecticut uses a graduated tax system with rates from 3% to 6.99%. The 5.5% rate applies to income from $10,000 to $50,000 (single). Higher earners face a top rate of 6.99%.', brackets: '3% to 6.99% across 7 brackets' },
  { slug: 'delaware', name: 'Delaware', abbreviation: 'DE', stateTaxRate: 5.2, hasNoIncomeTax: false, notes: 'Delaware uses a graduated income tax from 0% to 6.6%. There is no sales tax in Delaware, which offsets some of the income tax burden for residents.', brackets: '0% to 6.6% across 7 brackets; top rate over $60,000' },
  { slug: 'florida', name: 'Florida', abbreviation: 'FL', stateTaxRate: 0, hasNoIncomeTax: true, notes: 'Florida has no state income tax — one of seven states with zero state-level income tax. Florida relies heavily on sales tax (6% base rate) and tourism revenue. This makes Florida particularly attractive for high-income earners.', brackets: 'No state income tax' },
  { slug: 'georgia', name: 'Georgia', abbreviation: 'GA', stateTaxRate: 5.49, hasNoIncomeTax: false, notes: 'Georgia is transitioning to a flat income tax. The rate was 5.75% and is reducing by 0.1% annually, reaching 5.49% in 2024 and targeting 4.99% by 2029. This flat tax replaced a 6-bracket graduated system.', brackets: 'Flat 5.49% (reducing annually toward 4.99%)' },
  { slug: 'hawaii', name: 'Hawaii', abbreviation: 'HI', stateTaxRate: 8.25, hasNoIncomeTax: false, notes: 'Hawaii has one of the highest state income tax rates with 12 brackets ranging from 1.4% to 11%. The top rate of 11% applies to income over $400,000. For median earners, the effective rate is approximately 7-9%.', brackets: '1.4% to 11% across 12 brackets' },
  { slug: 'idaho', name: 'Idaho', abbreviation: 'ID', stateTaxRate: 5.8, hasNoIncomeTax: false, notes: 'Idaho simplified its income tax to a flat 5.8% rate in 2023, reduced from a graduated system that topped at 6%. The flat structure applies to all taxable income.', brackets: 'Flat 5.8%' },
  { slug: 'illinois', name: 'Illinois', abbreviation: 'IL', stateTaxRate: 4.95, hasNoIncomeTax: false, notes: 'Illinois has a flat 4.95% income tax rate mandated by the state constitution. A 2020 ballot measure to replace this with a graduated system was defeated by voters.', brackets: 'Flat 4.95% (constitutionally mandated)' },
  { slug: 'indiana', name: 'Indiana', abbreviation: 'IN', stateTaxRate: 3.05, hasNoIncomeTax: false, notes: 'Indiana uses a flat 3.05% state income tax rate (reduced from 3.15% in 2024). Note that Indiana counties also levy their own income taxes, adding 0.5% to 2.9% depending on where you live and work.', brackets: 'Flat 3.05% state + county tax (0.5%-2.9%)' },
  { slug: 'iowa', name: 'Iowa', abbreviation: 'IA', stateTaxRate: 3.8, hasNoIncomeTax: false, notes: 'Iowa is phasing in a flat tax. In 2024 the rate is 5.7% (two brackets); in 2025 it drops to a single flat rate. The eventual target is a flat 3.8% by 2025.', brackets: 'Flat 3.8% as of 2025' },
  { slug: 'kansas', name: 'Kansas', abbreviation: 'KS', stateTaxRate: 4.6, hasNoIncomeTax: false, notes: 'Kansas uses a graduated income tax with three brackets: 3.1%, 5.25%, and 5.7%. The top 5.7% rate applies to income over $30,000 (single).', brackets: '3.1% (under $15,000), 5.25% ($15,000-$30,000), 5.7% (over $30,000)' },
  { slug: 'kentucky', name: 'Kentucky', abbreviation: 'KY', stateTaxRate: 4.0, hasNoIncomeTax: false, notes: 'Kentucky implemented a flat 4.0% income tax rate in 2023 (down from 4.5%), with a legislated path to further reductions. Additional local occupational taxes may apply in some cities.', brackets: 'Flat 4.0%' },
  { slug: 'louisiana', name: 'Louisiana', abbreviation: 'LA', stateTaxRate: 3.5, hasNoIncomeTax: false, notes: 'Louisiana enacted a flat 3% income tax rate effective 2025 (previously 1.85%-4.25% graduated). The state also has a below-average standard deduction structure.', brackets: 'Flat 3% as of 2025' },
  { slug: 'maine', name: 'Maine', abbreviation: 'ME', stateTaxRate: 6.75, hasNoIncomeTax: false, notes: 'Maine has a graduated income tax with three rates: 5.8%, 6.75%, and 7.15%. The top 7.15% rate applies to income over $58,050 (single). A 3% surcharge applies to income over $75,000 for a total effective top rate near 10.15%.', brackets: '5.8%, 6.75%, 7.15%; surtax on high incomes' },
  { slug: 'maryland', name: 'Maryland', abbreviation: 'MD', stateTaxRate: 5.5, hasNoIncomeTax: false, notes: 'Maryland has a graduated state tax from 2% to 5.75%, plus a mandatory county income tax (2.25%-3.2%). The combined effective rate for median earners is typically 7-8%.', brackets: '2% to 5.75% state + 2.25%-3.2% county income tax' },
  { slug: 'massachusetts', name: 'Massachusetts', abbreviation: 'MA', stateTaxRate: 5.0, hasNoIncomeTax: false, notes: 'Massachusetts has a flat 5% income tax rate for most income. A 4% surtax (Millionaires Tax) applies to income over $1 million, bringing the effective rate to 9% for very high earners.', brackets: 'Flat 5%; 9% on income over $1M (4% surtax)' },
  { slug: 'michigan', name: 'Michigan', abbreviation: 'MI', stateTaxRate: 4.25, hasNoIncomeTax: false, notes: 'Michigan has a flat 4.25% state income tax rate. Additionally, many Michigan cities levy their own income taxes (1-2.4%), with Detroit at 2.4% for residents.', brackets: 'Flat 4.25% state + city tax in some areas' },
  { slug: 'minnesota', name: 'Minnesota', abbreviation: 'MN', stateTaxRate: 7.0, hasNoIncomeTax: false, notes: 'Minnesota has four tax brackets ranging from 5.35% to 9.85%. The 9.85% top rate is among the highest in the US. For median earners, the effective rate is typically 6-7%.', brackets: '5.35%, 6.8%, 7.85%, 9.85% across 4 brackets' },
  { slug: 'mississippi', name: 'Mississippi', abbreviation: 'MS', stateTaxRate: 4.7, hasNoIncomeTax: false, notes: 'Mississippi is phasing out its income tax. As of 2024 the top rate is 4.7%, phasing down to 0% by 2030. Mississippi was the first state to actively phase out its income tax.', brackets: 'Phasing to 0%: 4.7% in 2024, reducing annually' },
  { slug: 'missouri', name: 'Missouri', abbreviation: 'MO', stateTaxRate: 4.8, hasNoIncomeTax: false, notes: 'Missouri has a graduated tax with a top rate of 4.8% (reduced from 5.3% in 2023). The top rate applies to income over $8,968. Additional city taxes apply in Kansas City and St. Louis.', brackets: 'Top 4.8% (over $8,968); city taxes in KC and STL' },
  { slug: 'montana', name: 'Montana', abbreviation: 'MT', stateTaxRate: 6.75, hasNoIncomeTax: false, notes: 'Montana uses two income tax brackets: 4.7% on the first $20,500 and 6.75% on income above that. Montana has no sales tax, which partially offsets the income tax burden.', brackets: '4.7% (first $20,500), 6.75% (over $20,500)' },
  { slug: 'nebraska', name: 'Nebraska', abbreviation: 'NE', stateTaxRate: 5.84, hasNoIncomeTax: false, notes: 'Nebraska is reducing its top income tax rate to a flat 3.99% by 2027. As of 2024, the top rate is 5.84% (down from 6.84%). The state uses four graduated brackets.', brackets: '2.46% to 5.84% (phasing to flat 3.99% by 2027)' },
  { slug: 'nevada', name: 'Nevada', abbreviation: 'NV', stateTaxRate: 0, hasNoIncomeTax: true, notes: 'Nevada has no state income tax, relying instead on gaming taxes, sales taxes (6.85% base), and tourism revenue. This makes Nevada attractive for remote workers and retirees.', brackets: 'No state income tax' },
  { slug: 'new-hampshire', name: 'New Hampshire', abbreviation: 'NH', stateTaxRate: 0, hasNoIncomeTax: true, notes: 'New Hampshire has no state income tax on wages or salary. It previously taxed interest and dividend income at 3% (2024), but this tax is being phased out and will be fully eliminated by 2025.', brackets: 'No income tax on wages; dividend tax phasing out' },
  { slug: 'new-jersey', name: 'New Jersey', abbreviation: 'NJ', stateTaxRate: 5.53, hasNoIncomeTax: false, notes: 'New Jersey has a graduated income tax from 1.4% to 10.75% with six brackets. Property taxes in New Jersey are among the highest in the country. The top 10.75% rate applies to income over $1 million.', brackets: '1.4% to 10.75% across 6 brackets; top rate over $1M' },
  { slug: 'new-mexico', name: 'New Mexico', abbreviation: 'NM', stateTaxRate: 4.9, hasNoIncomeTax: false, notes: 'New Mexico uses a graduated income tax from 1.7% to 5.9% with five brackets. The 5.9% top rate applies to income over $210,000 (single). For median earners, the effective rate is approximately 4-5%.', brackets: '1.7% to 5.9% across 5 brackets' },
  { slug: 'new-york', name: 'New York', abbreviation: 'NY', stateTaxRate: 6.85, hasNoIncomeTax: false, notes: 'New York has a graduated state tax from 4% to 10.9% with eight brackets. New York City residents pay an additional city tax of 3.078% to 3.876%. New York State and City together create one of the highest combined income tax burdens in the US.', brackets: '4% to 10.9% state; +3.1%-3.9% NYC city tax' },
  { slug: 'north-carolina', name: 'North Carolina', abbreviation: 'NC', stateTaxRate: 4.5, hasNoIncomeTax: false, notes: 'North Carolina moved to a flat income tax of 4.5% in 2024. It is reducing to 4.25% in 2025 and has a legislated path toward 2.49% by 2030. Previously a 5.25% flat rate.', brackets: 'Flat 4.5% (reducing annually)' },
  { slug: 'north-dakota', name: 'North Dakota', abbreviation: 'ND', stateTaxRate: 1.1, hasNoIncomeTax: false, notes: 'North Dakota significantly reduced its income tax in 2023. Single filers with income under $44,725 now pay 0%. Above that threshold the rate is a flat 1.1%. This makes North Dakota one of the lowest-tax states for wage earners.', brackets: '0% (under $44,725), 1.1% (over $44,725) for single filers' },
  { slug: 'ohio', name: 'Ohio', abbreviation: 'OH', stateTaxRate: 3.5, hasNoIncomeTax: false, notes: 'Ohio uses a graduated income tax with a top rate of 3.5% on income over $115,300. Income under $26,050 is exempt from state tax. Many Ohio cities also levy a municipal income tax (typically 2-2.5%).', brackets: '0% (under $26,050), graduated to 3.5%; city taxes apply' },
  { slug: 'oklahoma', name: 'Oklahoma', abbreviation: 'OK', stateTaxRate: 4.75, hasNoIncomeTax: false, notes: 'Oklahoma has a graduated income tax from 0.25% to 4.75% with five brackets. The top 4.75% rate applies to income over $7,200 for single filers — one of the lowest top-bracket thresholds in the US.', brackets: '0.25% to 4.75% across 5 brackets; top rate kicks in at $7,200' },
  { slug: 'oregon', name: 'Oregon', abbreviation: 'OR', stateTaxRate: 9.0, hasNoIncomeTax: false, notes: 'Oregon has a graduated income tax from 4.75% to 9.9% with four brackets. The 9.9% top rate applies to income over $125,000 (single). Oregon has no sales tax, which partially offsets the income tax burden. Portland metro area residents face an additional Metro/Multnomah County tax.', brackets: '4.75% to 9.9% across 4 brackets; no sales tax' },
  { slug: 'pennsylvania', name: 'Pennsylvania', abbreviation: 'PA', stateTaxRate: 3.07, hasNoIncomeTax: false, notes: 'Pennsylvania has a flat 3.07% state income tax rate. Additionally, most Pennsylvania municipalities levy a local earned income tax (typically 1-3%). Philadelphia residents pay an additional city wage tax of 3.75%.', brackets: 'Flat 3.07% state + local earned income tax' },
  { slug: 'rhode-island', name: 'Rhode Island', abbreviation: 'RI', stateTaxRate: 4.75, hasNoIncomeTax: false, notes: 'Rhode Island uses a graduated income tax with three brackets: 3.75%, 4.75%, and 5.99%. The 5.99% top rate applies to income over $176,050.', brackets: '3.75%, 4.75%, 5.99% across 3 brackets' },
  { slug: 'south-carolina', name: 'South Carolina', abbreviation: 'SC', stateTaxRate: 6.4, hasNoIncomeTax: false, notes: 'South Carolina is reducing its top income tax rate. In 2024 the top rate is 6.4%, phasing down 0.1% annually to 6.0% and potentially lower. The top rate applies to income over $17,330.', brackets: '3%, 4%, 5%, 6.4% (reducing); top rate over $17,330' },
  { slug: 'south-dakota', name: 'South Dakota', abbreviation: 'SD', stateTaxRate: 0, hasNoIncomeTax: true, notes: 'South Dakota has no state income tax, relying on sales taxes and other revenue. It is one of seven no-income-tax states. The state has no corporate income tax either.', brackets: 'No state income tax' },
  { slug: 'tennessee', name: 'Tennessee', abbreviation: 'TN', stateTaxRate: 0, hasNoIncomeTax: true, notes: 'Tennessee has no state income tax on wages or salary. A previous tax on investment income (dividends and interest) called the Hall Tax was fully eliminated in 2021. Tennessee is one of seven states with no income tax.', brackets: 'No state income tax' },
  { slug: 'texas', name: 'Texas', abbreviation: 'TX', stateTaxRate: 0, hasNoIncomeTax: true, notes: 'Texas has no state income tax, one of only seven such states. Texas generates revenue primarily through property taxes (among the highest nationally) and sales taxes (6.25% base). No corporate income tax either.', brackets: 'No state income tax' },
  { slug: 'utah', name: 'Utah', abbreviation: 'UT', stateTaxRate: 4.65, hasNoIncomeTax: false, notes: 'Utah has a flat 4.65% state income tax rate. Utah also offers a nonrefundable credit for taxpayers equal to 6% of the federal standard deduction, which effectively reduces the tax burden for lower earners.', brackets: 'Flat 4.65%' },
  { slug: 'vermont', name: 'Vermont', abbreviation: 'VT', stateTaxRate: 6.6, hasNoIncomeTax: false, notes: 'Vermont uses a graduated income tax from 3.35% to 8.75% with four brackets. The 8.75% top rate applies to income over $213,150 (single). Vermont has among the highest total tax burdens in the US.', brackets: '3.35%, 6.6%, 7.6%, 8.75% across 4 brackets' },
  { slug: 'virginia', name: 'Virginia', abbreviation: 'VA', stateTaxRate: 5.75, hasNoIncomeTax: false, notes: 'Virginia uses a graduated income tax from 2% to 5.75%. The top 5.75% rate applies to income over $17,000, meaning most working adults pay at or near the top rate. Virginia has been expanding its standard deduction in recent years.', brackets: '2%, 3%, 5%, 5.75%; top rate over $17,000' },
  { slug: 'washington', name: 'Washington', abbreviation: 'WA', stateTaxRate: 0, hasNoIncomeTax: true, notes: 'Washington has no state income tax — one of seven no-income-tax states. Washington relies heavily on a 6.5% sales tax. Note: Washington enacted a 7% capital gains tax in 2022 on gains over $250,000, but this applies only to investment income, not wages.', brackets: 'No state income tax on wages; 7% capital gains tax on gains over $250K' },
  { slug: 'west-virginia', name: 'West Virginia', abbreviation: 'WV', stateTaxRate: 5.12, hasNoIncomeTax: false, notes: 'West Virginia is reducing its income tax rates. As of 2024, the top rate is 5.12% (down from 6.5%). There are plans to further reduce it. The state uses a graduated system with five brackets.', brackets: '3%, 4%, 4.5%, 6%, 6.5% (phasing down)' },
  { slug: 'wisconsin', name: 'Wisconsin', abbreviation: 'WI', stateTaxRate: 5.3, hasNoIncomeTax: false, notes: 'Wisconsin has a graduated income tax with four brackets ranging from 3.54% to 7.65%. The 5.3% figure represents a typical effective rate for median earners. The top 7.65% rate applies to income over $304,600 for single filers.', brackets: '3.54%, 4.65%, 5.3%, 7.65% across 4 brackets' },
  { slug: 'wyoming', name: 'Wyoming', abbreviation: 'WY', stateTaxRate: 0, hasNoIncomeTax: true, notes: 'Wyoming has no state income tax — one of seven no-income-tax states. Wyoming generates revenue from mineral extraction (oil, gas, coal) and sales taxes. Wyoming also has no corporate income tax.', brackets: 'No state income tax' },
  { slug: 'district-of-columbia', name: 'District of Columbia', abbreviation: 'DC', stateTaxRate: 8.25, hasNoIncomeTax: false, notes: 'Washington DC uses a graduated income tax from 4% to 10.75% with six brackets. The 10.75% top rate applies to income over $1 million. DC residents pay DC taxes only; they do not pay Maryland or Virginia taxes.', brackets: '4% to 10.75% across 6 brackets; top rate over $1M' },
]

export function getStateBySlug(slug: string): StateData | undefined {
  return US_STATES.find(s => s.slug === slug)
}

export function getAllStateSlugs(): string[] {
  return US_STATES.map(s => s.slug)
}
